version: '3.8'

services:
  backend:
    build:
      context: ./appToDoBackend
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - database

  frontend:
    build:
      context: ./appToDoFrontend
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    depends_on:
      - backend

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: user_3000
    ports:
      - "5433:5432"
