version: '3.8'

services:
  backend:
    build:
      context: ./appToDoBackend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
        - ./appToDoBackend:/app
    depends_on:
      - database

  frontend:
    build:
      context: ./appToDoFrontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./appToDoFrontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: bash -c "npm install && npm start"

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: user_3000
    ports:
      - "5432:5432"
